### ISSUE TITLE
Can't ever start a new cdda map

### ISSUE THREAD

**Issue by Maleclypse** [solerante/cdda-tiled-extension#123]
I always get this error 
```
Error: Could not open file for writing.
Stack traceback:
  makeEmptyMap@file:///C:/Users/colli/AppData/Local/Tiled/extensions/cdda_map_extension_extras/CDDA_Map_extension.mjs:1947
  @file:///C:/Users/colli/AppData/Local/Tiled/extensions/cdda_map_extension_extras/CDDA_Map_extension.mjs:2576
```

**Comment by solerante** [comment]
@Maleclypse not sure if the issue resolved itself on your end, but if using tiled 1.8, you would have to use the version in the latest release. For tiled 1.10, rather than just updating it, I've been redoing most of the code, so unfortunately there is no compatible version for tiled 1.10.
